name: avalia_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Simulator of many types of devices
  device_preview: ^0.4.8
  #Fundamental of Firebase
  firebase_core: ^0.5.0
  #Access the database of Google Firebase
  cloud_firestore: ^0.14.0+2
  #Authenticate user of Google Firebase
  firebase_auth: ^0.18.0+1
  #Can storage file in the Google Firebase
  firebase_storage: ^4.0.0
  #Access the Camara and the Image Gallery
  image_picker: ^0.6.7+4
  #Access directories of the resource
  path_provider: ^1.6.11
  #To verify if there is connection with the internet
  data_connection_checker: ^0.3.4
  #To resizes FontSize automatically
  auto_size_text: ^2.1.0
  #To use the class NumberFormat, package of internalionization
  intl: ^0.16.1
  #To show the progress bar
  percent_indicator: ^2.1.5
  #To user circular checkbox
  circular_check_box: ^1.0.4
  #To show a custom scrollbar
  draggable_scrollbar: ^0.0.4
  #To save user e-mail in the phone
  shared_preferences: ^0.5.12
  #To disable buttom home
  hardware_buttons: 0.2.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/avalia.png"
  adaptive_icon_background: "#4B81C2"
  adaptive_icon_foreground: 'dev_assets/avalia_adaptive.png'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Some application icons
  assets:
    - lib/res/icons/icon_edit_profile.png
    - lib/res/icons/icon_logo.png
    - lib/res/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quenda
      fonts:
        - asset: lib/res/fonts/Quenda-Medium.otf
    - family: CustomButtonIcon
      fonts:
        - asset: lib/res/icons/Custom-Button-Icon.ttf
    - family: CustomIcon
      fonts:
        - asset: lib/res/icons/Custom-Icon.ttf
   
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
